# Generated by Django 3.2.6 on 2021-08-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=255)),
                ('respuestaCorr', models.CharField(max_length=255)),
                ('rtaInc1', models.CharField(max_length=255)),
                ('rtaInc2', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
                ('nivel', models.IntegerField()),
            ],
            options={
                'db_table': 'Preguntas',
            },
        ),
    ]
