# Generated by Django 3.2.6 on 2021-08-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=255)),
                ('respuesta', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Preguntas',
            },
        ),
    ]
