# Generated by Django 3.2.6 on 2021-08-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elegirrespuesta',
            name='consigna',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='consigna',
            field=models.CharField(max_length=255),
        ),
    ]
